version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persistent model cache

  app:
    build: ./app
    depends_on:
      - ollama

volumes:
  ollama_models:
